name:                klaraworks-api
version:             0.0.0.2
github:              "kirisaki/klaraworks-api"
license:             MIT
author:              "Akihito KIRISAKI"
maintainer:          "kirisaki@klaraworks.net"
copyright:           "2018 Akihito Kirisaki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/paprika-server#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- cookie
- elm-export
- esqueleto
- mtl
- monad-logger
- servant
- servant-server
- servant-elm
- persistent
- persistent-template
- persistent-sqlite
- resourcet
- random
- text
- time
- transformers
- wai
- wai-app-static
- wai-logger
- warp

library:
  source-dirs: src

executables:
  klaraworks:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - klaraworks-api

tests:
  klaraworks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - klaraworks-api
